// SuperDeck Themes - colour palettes and font pairings
export var THEMES = {
  midnight: {
    name: 'Midnight executive',
    primary: '#1e1b4b',
    secondary: '#312e81',
    accent: '#8b5cf6',
    text: '#ffffff',
    muted: '#a5b4fc',
    surface: '#0f0e2a',
    headingFont: 'Sora, sans-serif',
    bodyFont: 'DM Sans, sans-serif',
  },
  ocean: {
    name: 'Ocean depth',
    primary: '#0c4a6e',
    secondary: '#075985',
    accent: '#0ea5e9',
    text: '#ffffff',
    muted: '#7dd3fc',
    surface: '#082f49',
    headingFont: 'Sora, sans-serif',
    bodyFont: 'DM Sans, sans-serif',
  },
  forest: {
    name: 'Forest green',
    primary: '#14532d',
    secondary: '#166534',
    accent: '#22c55e',
    text: '#ffffff',
    muted: '#86efac',
    surface: '#052e16',
    headingFont: 'Sora, sans-serif',
    bodyFont: 'DM Sans, sans-serif',
  },
  coral: {
    name: 'Coral energy',
    primary: '#7f1d1d',
    secondary: '#991b1b',
    accent: '#f97316',
    text: '#ffffff',
    muted: '#fca5a5',
    surface: '#450a0a',
    headingFont: 'Sora, sans-serif',
    bodyFont: 'DM Sans, sans-serif',
  },
  minimal: {
    name: 'Clean white',
    primary: '#ffffff',
    secondary: '#f8fafc',
    accent: '#0f172a',
    text: '#0f172a',
    muted: '#64748b',
    surface: '#f1f5f9',
    headingFont: 'Sora, sans-serif',
    bodyFont: 'DM Sans, sans-serif',
  },
  charcoal: {
    name: 'Charcoal',
    primary: '#1c1917',
    secondary: '#292524',
    accent: '#f59e0b',
    text: '#fafaf9',
    muted: '#a8a29e',
    surface: '#0c0a09',
    headingFont: 'Sora, sans-serif',
    bodyFont: 'DM Sans, sans-serif',
  },
};

export var THEME_KEYS = Object.keys(THEMES);

export var SLIDE_LAYOUTS = [
  { key: 'title', name: 'Title slide', desc: 'Big centred heading + subtitle' },
  { key: 'content', name: 'Content', desc: 'Heading + body text' },
  { key: 'twoCol', name: 'Two column', desc: 'Text left, image right' },
  { key: 'imageRight', name: 'Image + text', desc: 'Image right, text left' },
  { key: 'stats', name: 'Stats', desc: 'Big numbers with labels' },
  { key: 'quote', name: 'Quote', desc: 'Large centred quote' },
  { key: 'bullets', name: 'Bullet list', desc: 'Heading + bullet points' },
  { key: 'closing', name: 'Closing', desc: 'Thank you / CTA slide' },
];
